package com.techchallenge.restaurant.application.exception;

public enum ErrorCode {
  EMAIL_ALREADY_EXISTS,
  LOGIN_ALREADY_EXISTS,
  USER_NOT_FOUND,
  INVALID_PASSWORD,
  USER_TYPE_NOT_FOUND,
  USER_TYPE_ALREADY_EXISTS,
  USER_TYPE_INVALID_NAME,
  USER_TYPE_IN_USE,
  RESTAURANT_NOT_FOUND,
  RESTAURANT_ALREADY_EXISTS,
  RESTAURANT_OWNER_NOT_FOUND,
  MENU_ITEM_NOT_FOUND,
  MENU_ITEM_ALREADY_EXISTS,
  MENU_ITEM_RESTAURANT_NOT_FOUND
}
